version: "3"
services:
  broker:
    container_name: broker
    ports:
      - 1883:1883
      - 8883:8883
      - 9883:9883
    # NOTE: comment out volumes for deploy, use config inside container 
    volumes:
      - $PWD/mosquitto-conf/:/mqtt/config/
    build:
      dockerfile: Dockerfile-broker-${ARCH:-x86}
      context: .
  #filebeat:
  #  container_name: filebeat
  #  volumes:
  #    - $PWD/filebeat-conf/config/filebeat.yml:/usr/share/filebeat/config/filebeat.yml
  #    - /usr/share/filebeat/data
  #  build:
  #    dockerfile: Dockerfile-filebeat-${ARCH:-x86}
  #    context: .
  node-red:
    # see https://hub.docker.com/r/nodered/node-red-docker/
    container_name: node-red
    privileged: true
    volumes:
      - ./node-red:/data
      - ./certs:/certs
    links:
      - broker
    build:
      dockerfile: Dockerfile-nodered-${ARCH:-x86}
      context: .
  nginx:
    # see https://store.docker.com/images/nginx?tab=description
    image: nginx
    container_name: nginx
    restart: unless-stopped
    links:
      - node-red
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - SERVER:${SERVER:-iotlab.local}
    command: nginx -g 'daemon off;'
    
