version: "3"
services:
  broker:
    container_name: broker
    ports:
      - 1883:1883
      - 8883:8883
      - 9883:9883
      - 18883:18883
    volumes:
      - ./mosquitto-conf/:/mqtt/config/
      - ./mosquitto-data/:/mqtt/data/
      - ./certs:/certs
    build:
      dockerfile: Dockerfile-broker-${ARCH:-x86}
      context: .
  node-red-trapcam:
    container_name: node-red-trapcam
    privileged: true
    volumes:
      - ./node-red-trapcam:/data
      - ./certs:/certs
      - /home/test/images:/data/static/images
    links:
      - broker
    image: iotlab_node-red
  nginx:
    # see https://store.docker.com/images/nginx?tab=description
    image: nginx
    container_name: nginx
    restart: unless-stopped
    links:
      - node-red-trapcam
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    environment:
      - SERVER:${SERVER:-iotlab.local}
    command: nginx -g 'daemon off;'
    
